spring:
  profiles: dev
server:
  port: 9000
---
spring:
  profiles: qa
server:
  port: 9001
---
spring:
  profiles:
    active: dev
---
management:
  security:
    enabled: false
---
logging:
  level:
    org.springframework.web: ERROR
    com.aa: DEBUG
email: onlyankur@gmail.com
thread-pool: 10
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
management:
  endpoint:
    health:
      show-details: "ALWAYS"


---
spring:
    security:
      user:
        name: ankur
        password: ankur
---
spring:
    mail:
      host: smtp.gmail.com
      username: onlyankur@gmail.com
      password: choclateicecream
      port: 587
      properties:
          mail:
            smtp:
                auth: true
                starttls: true
    boot:
        admin:
          notify:
              mail:
                to: onlyankur@gmail.com



